/*
 * NumOS — STIX Two Math Glyph Variant & Assembly Tables
 * Auto-generated by scripts/extract_stix_math.py on 2026-06-04 22:34:02
 * Source font: C:\Users\Juan Ramón\Documents\Calculadora\assets\fonts\STIXTwoMath-Regular.ttf
 * Font UPM (unitsPerEm): 1000
 *
 * All values are in font design units (UPM = 1000).
 * Scale to pixels by multiplying by (fontSizePx / upm).
 *
 * Reference: OpenType 1.9.1, MATH table — MathVariants sub-table.
 */

#pragma once

#include <cstdint>

namespace vpam {

// ════════════════════════════════════════════════════════════════════════════
// GlyphPartRecord — Single piece in a vertical glyph assembly
//
// OpenType stores assembly parts bottom-to-top. The DelimiterAssembler FSM
// reorders them top-to-bottom for execution in the renderer.
//
// Parts overlap by startConnector / endConnector lengths to eliminate
// visual seams (rasterisation gaps) on low-resolution displays.
// ════════════════════════════════════════════════════════════════════════════
struct GlyphPartRecord {
    uint32_t glyphCp;            ///< Unicode codepoint
    int16_t  fullAdvance;        ///< Full glyph height in design units
    int16_t  glyphWidth;         ///< Horizontal advance width in design units
    int16_t  startConnector;     ///< Connector length at glyph start (DU)
    int16_t  endConnector;       ///< Connector length at glyph end (DU)
    bool     isExtender;         ///< Repeatable piece that fills the middle
};

// ════════════════════════════════════════════════════════════════════════════
// SizeVariantRecord — Discrete larger variant of a base glyph
//
// Used when the target height fits within the variant's height without
// needing assembly. Variants are listed in increasing height order.
// ════════════════════════════════════════════════════════════════════════════
struct SizeVariantRecord {
    uint32_t glyphCp;            ///< Unicode codepoint of the variant
    int16_t  height;             ///< Glyph height in design units
    int16_t  glyphWidth;         ///< Horizontal advance width in design units
};

// ════════════════════════════════════════════════════════════════════════════
// MathVariantTable — Complete variant data for one delimiter/operator
//
// Each table covers one base glyph and enumerates:
//   1. The base glyph's natural height and width
//   2. Size variants (increasing height) — used before falling back to assembly
//   3. Assembly parts (stored bottom-to-top per OpenType) — used for tall content
// ════════════════════════════════════════════════════════════════════════════
struct MathVariantTable {
    uint32_t baseCodepoint;          ///< Base glyph (e.g. U+0028 for '(')
    int16_t  baseHeight;             ///< Base glyph height in design units
    int16_t  baseWidth;              ///< Base glyph horizontal advance in design units
    const SizeVariantRecord* sizeVariants;
    uint8_t  sizeVariantCount;
    const GlyphPartRecord*  assemblyParts;
    uint8_t  assemblyPartCount;
    int16_t  italicsCorrection;      ///< MathItalicsCorrection in design units
};

// ════════════════════════════════════════════════════════════════════════════
// Static Variant Tables — dynamically extracted from font
// ════════════════════════════════════════════════════════════════════════════

// ── U+0028 ─────────────────────────────────────────────────────────
inline constexpr SizeVariantRecord kVarTable_0028_sv[] = {
    { 0x0028,   933,   357 },  // U+0028
};

inline constexpr GlyphPartRecord kVarTable_0028_parts[] = {
    { 0x239D,  1273,   484,    0,  250, false },  // U+239D
    { 0x239C,  1252,   484, 1000, 1000, true },  // U+239C
    { 0x239B,  1273,   484,  250,    0, false },  // U+239B
};

inline constexpr MathVariantTable kVarTable_0028 = {
    0x0028,          // baseCodepoint
    700,             // baseHeight (DU)
    357,             // baseWidth  (DU)
    kVarTable_0028_sv, 1,  // sizeVariants
    kVarTable_0028_parts, 3,  // assemblyParts
    0,               // italicsCorrection
};


// ── U+0029 ─────────────────────────────────────────────────────────
inline constexpr SizeVariantRecord kVarTable_0029_sv[] = {
    { 0x0029,   933,   357 },  // U+0029
};

inline constexpr GlyphPartRecord kVarTable_0029_parts[] = {
    { 0x23A0,  1273,   484,    0,  250, false },  // U+23A0
    { 0x239F,  1252,   484, 1000, 1000, true },  // U+239F
    { 0x239E,  1273,   484,  250,    0, false },  // U+239E
};

inline constexpr MathVariantTable kVarTable_0029 = {
    0x0029,          // baseCodepoint
    700,             // baseHeight (DU)
    357,             // baseWidth  (DU)
    kVarTable_0029_sv, 1,  // sizeVariants
    kVarTable_0029_parts, 3,  // assemblyParts
    0,               // italicsCorrection
};


// ── U+005B ─────────────────────────────────────────────────────────
inline constexpr SizeVariantRecord kVarTable_005B_sv[] = {
    { 0x005B,   933,   349 },  // U+005B
};

inline constexpr GlyphPartRecord kVarTable_005B_parts[] = {
    { 0x23A3,  1275,   585,    0, 1200, false },  // U+23A3
    { 0x23A2,  1001,   585, 1000, 1000, true },  // U+23A2
    { 0x23A1,  1275,   585, 1200,    0, false },  // U+23A1
};

inline constexpr MathVariantTable kVarTable_005B = {
    0x005B,          // baseCodepoint
    700,             // baseHeight (DU)
    349,             // baseWidth  (DU)
    kVarTable_005B_sv, 1,  // sizeVariants
    kVarTable_005B_parts, 3,  // assemblyParts
    0,               // italicsCorrection
};


// ── U+005D ─────────────────────────────────────────────────────────
inline constexpr SizeVariantRecord kVarTable_005D_sv[] = {
    { 0x005D,   933,   349 },  // U+005D
};

inline constexpr GlyphPartRecord kVarTable_005D_parts[] = {
    { 0x23A6,  1275,   585,    0, 1200, false },  // U+23A6
    { 0x23A5,  1001,   585, 1000, 1000, true },  // U+23A5
    { 0x23A4,  1275,   585, 1200,    0, false },  // U+23A4
};

inline constexpr MathVariantTable kVarTable_005D = {
    0x005D,          // baseCodepoint
    700,             // baseHeight (DU)
    349,             // baseWidth  (DU)
    kVarTable_005D_sv, 1,  // sizeVariants
    kVarTable_005D_parts, 3,  // assemblyParts
    0,               // italicsCorrection
};


// ── U+007B ─────────────────────────────────────────────────────────
inline constexpr SizeVariantRecord kVarTable_007B_sv[] = {
    { 0x007B,   934,   327 },  // U+007B
};

inline constexpr GlyphPartRecord kVarTable_007B_parts[] = {

};

inline constexpr MathVariantTable kVarTable_007B = {
    0x007B,          // baseCodepoint
    700,             // baseHeight (DU)
    327,             // baseWidth  (DU)
    kVarTable_007B_sv, 1,  // sizeVariants
    nullptr, 0,  // assemblyParts
    0,               // italicsCorrection
};


// ── U+007D ─────────────────────────────────────────────────────────
inline constexpr SizeVariantRecord kVarTable_007D_sv[] = {
    { 0x007D,   934,   327 },  // U+007D
};

inline constexpr GlyphPartRecord kVarTable_007D_parts[] = {

};

inline constexpr MathVariantTable kVarTable_007D = {
    0x007D,          // baseCodepoint
    700,             // baseHeight (DU)
    327,             // baseWidth  (DU)
    kVarTable_007D_sv, 1,  // sizeVariants
    nullptr, 0,  // assemblyParts
    0,               // italicsCorrection
};


// ── U+007C ─────────────────────────────────────────────────────────
inline constexpr SizeVariantRecord kVarTable_007C_sv[] = {
    { 0x007C,   927,   267 },  // U+007C
};

inline constexpr GlyphPartRecord kVarTable_007C_parts[] = {

};

inline constexpr MathVariantTable kVarTable_007C = {
    0x007C,          // baseCodepoint
    700,             // baseHeight (DU)
    267,             // baseWidth  (DU)
    kVarTable_007C_sv, 1,  // sizeVariants
    nullptr, 0,  // assemblyParts
    0,               // italicsCorrection
};


// ── U+2211 ─────────────────────────────────────────────────────────
inline constexpr SizeVariantRecord kVarTable_2211_sv[] = {
    { 0x2211,  1031,   936 },  // U+2211
};

inline constexpr GlyphPartRecord kVarTable_2211_parts[] = {

};

inline constexpr MathVariantTable kVarTable_2211 = {
    0x2211,          // baseCodepoint
    936,             // baseHeight (DU)
    936,             // baseWidth  (DU)
    kVarTable_2211_sv, 1,  // sizeVariants
    nullptr, 0,  // assemblyParts
    0,               // italicsCorrection
};


// ── U+220F ─────────────────────────────────────────────────────────
inline constexpr SizeVariantRecord kVarTable_220F_sv[] = {
    { 0x220F,  1031,  1135 },  // U+220F
};

inline constexpr GlyphPartRecord kVarTable_220F_parts[] = {

};

inline constexpr MathVariantTable kVarTable_220F = {
    0x220F,          // baseCodepoint
    1135,             // baseHeight (DU)
    1135,             // baseWidth  (DU)
    kVarTable_220F_sv, 1,  // sizeVariants
    nullptr, 0,  // assemblyParts
    0,               // italicsCorrection
};


// ── U+2210 ─────────────────────────────────────────────────────────
inline constexpr SizeVariantRecord kVarTable_2210_sv[] = {
    { 0x2210,  1031,  1135 },  // U+2210
};

inline constexpr GlyphPartRecord kVarTable_2210_parts[] = {

};

inline constexpr MathVariantTable kVarTable_2210 = {
    0x2210,          // baseCodepoint
    1135,             // baseHeight (DU)
    1135,             // baseWidth  (DU)
    kVarTable_2210_sv, 1,  // sizeVariants
    nullptr, 0,  // assemblyParts
    0,               // italicsCorrection
};


// ── U+22C0 ─────────────────────────────────────────────────────────
inline constexpr SizeVariantRecord kVarTable_22C0_sv[] = {
    { 0x22C0,  1047,   946 },  // U+22C0
};

inline constexpr GlyphPartRecord kVarTable_22C0_parts[] = {

};

inline constexpr MathVariantTable kVarTable_22C0 = {
    0x22C0,          // baseCodepoint
    946,             // baseHeight (DU)
    946,             // baseWidth  (DU)
    kVarTable_22C0_sv, 1,  // sizeVariants
    nullptr, 0,  // assemblyParts
    0,               // italicsCorrection
};


// ── U+22C1 ─────────────────────────────────────────────────────────
inline constexpr SizeVariantRecord kVarTable_22C1_sv[] = {
    { 0x22C1,  1047,   946 },  // U+22C1
};

inline constexpr GlyphPartRecord kVarTable_22C1_parts[] = {

};

inline constexpr MathVariantTable kVarTable_22C1 = {
    0x22C1,          // baseCodepoint
    946,             // baseHeight (DU)
    946,             // baseWidth  (DU)
    kVarTable_22C1_sv, 1,  // sizeVariants
    nullptr, 0,  // assemblyParts
    0,               // italicsCorrection
};


// ── U+22C2 ─────────────────────────────────────────────────────────
inline constexpr SizeVariantRecord kVarTable_22C2_sv[] = {
    { 0x22C2,  1057,   946 },  // U+22C2
};

inline constexpr GlyphPartRecord kVarTable_22C2_parts[] = {

};

inline constexpr MathVariantTable kVarTable_22C2 = {
    0x22C2,          // baseCodepoint
    946,             // baseHeight (DU)
    946,             // baseWidth  (DU)
    kVarTable_22C2_sv, 1,  // sizeVariants
    nullptr, 0,  // assemblyParts
    0,               // italicsCorrection
};


// ── U+22C3 ─────────────────────────────────────────────────────────
inline constexpr SizeVariantRecord kVarTable_22C3_sv[] = {
    { 0x22C3,  1058,   946 },  // U+22C3
};

inline constexpr GlyphPartRecord kVarTable_22C3_parts[] = {

};

inline constexpr MathVariantTable kVarTable_22C3 = {
    0x22C3,          // baseCodepoint
    946,             // baseHeight (DU)
    946,             // baseWidth  (DU)
    kVarTable_22C3_sv, 1,  // sizeVariants
    nullptr, 0,  // assemblyParts
    0,               // italicsCorrection
};


// ── U+222B ─────────────────────────────────────────────────────────
inline constexpr SizeVariantRecord kVarTable_222B_sv[] = {
    { 0x222B,   954,   684 },  // U+222B
};

inline constexpr GlyphPartRecord kVarTable_222B_parts[] = {

};

inline constexpr MathVariantTable kVarTable_222B = {
    0x222B,          // baseCodepoint
    700,             // baseHeight (DU)
    684,             // baseWidth  (DU)
    kVarTable_222B_sv, 1,  // sizeVariants
    nullptr, 0,  // assemblyParts
    230,               // italicsCorrection
};

// ════════════════════════════════════════════════════════════════════════════
// Lookup helper — returns the variant table for a known base codepoint
// ════════════════════════════════════════════════════════════════════════════
inline const MathVariantTable* lookupVariantTable(uint32_t baseCp) {
    switch (baseCp) {
        case 0x0028: return &kVarTable_0028;
        case 0x0029: return &kVarTable_0029;
        case 0x005B: return &kVarTable_005B;
        case 0x005D: return &kVarTable_005D;
        case 0x007B: return &kVarTable_007B;
        case 0x007D: return &kVarTable_007D;
        case 0x007C: return &kVarTable_007C;
        case 0x2211: return &kVarTable_2211;
        case 0x220F: return &kVarTable_220F;
        case 0x2210: return &kVarTable_2210;
        case 0x22C0: return &kVarTable_22C0;
        case 0x22C1: return &kVarTable_22C1;
        case 0x22C2: return &kVarTable_22C2;
        case 0x22C3: return &kVarTable_22C3;
        case 0x222B: return &kVarTable_222B;
        default:     return nullptr;
    }
}

}  // namespace vpam
