// Generated by scripts/generate-stix-parentheses.py; STIX OFL-1.1.
#pragma once
#include <cstdint>
namespace vpam {
struct StixParenInk { int16_t width, height, xOffset, yOffset, advance; };
inline constexpr StixParenInk kStixParens18[] = {
    {6, 18, 0, -4, 6}, // parenleft
    {7, 22, 0, -6, 7}, // parenleft.s1
    {7, 26, 0, -8, 7}, // parenleft.s2
    {7, 31, 1, -11, 8}, // parenleft.s3
    {7, 36, 1, -13, 8}, // parenleft.s4
    {7, 40, 1, -15, 9}, // parenleft.s5
    {8, 44, 1, -17, 9}, // parenleft.s6
    {8, 48, 1, -19, 9}, // parenleft.s7
    {8, 52, 1, -21, 10}, // parenleft.s8
    {9, 57, 1, -24, 10}, // parenleft.s9
    {10, 61, 1, -26, 11}, // parenleft.s10
    {10, 66, 1, -28, 11}, // parenleft.s11
    {10, 70, 1, -30, 11}, // parenleft.s12
    {8, 23, 0, 0, 9}, // uni239B
    {3, 24, 0, -1, 9}, // uni239C
    {8, 23, 0, 0, 9}, // uni239D
    {6, 18, 0, -4, 6}, // parenright
    {6, 22, 0, -6, 7}, // parenright.s1
    {7, 26, 0, -8, 7}, // parenright.s2
    {7, 31, 0, -11, 8}, // parenright.s3
    {7, 36, 0, -13, 8}, // parenright.s4
    {8, 40, 0, -15, 9}, // parenright.s5
    {8, 44, 0, -17, 9}, // parenright.s6
    {8, 48, 0, -19, 9}, // parenright.s7
    {9, 52, 0, -21, 10}, // parenright.s8
    {9, 57, 0, -24, 10}, // parenright.s9
    {9, 61, 0, -26, 11}, // parenright.s10
    {10, 66, 0, -28, 11}, // parenright.s11
    {10, 70, 0, -30, 11}, // parenright.s12
    {8, 23, 0, 0, 9}, // uni239E
    {3, 24, 5, -1, 9}, // uni239F
    {8, 23, 0, 0, 9}, // uni23A0
};
inline constexpr StixParenInk kStixParens12[] = {
    {4, 13, 0, -3, 4}, // parenleft
    {5, 15, 0, -4, 5}, // parenleft.s1
    {5, 18, 0, -6, 5}, // parenleft.s2
    {5, 21, 0, -7, 5}, // parenleft.s3
    {6, 24, 0, -9, 5}, // parenleft.s4
    {6, 27, 0, -10, 6}, // parenleft.s5
    {6, 30, 0, -12, 6}, // parenleft.s6
    {6, 32, 0, -13, 6}, // parenleft.s7
    {7, 35, 0, -14, 7}, // parenleft.s8
    {6, 38, 1, -16, 7}, // parenleft.s9
    {6, 41, 1, -17, 7}, // parenleft.s10
    {6, 44, 1, -19, 7}, // parenleft.s11
    {7, 47, 1, -20, 8}, // parenleft.s12
    {6, 16, 0, 0, 6}, // uni239B
    {2, 16, 0, -1, 6}, // uni239C
    {6, 16, 0, 0, 6}, // uni239D
    {4, 13, 0, -3, 4}, // parenright
    {4, 15, 0, -4, 5}, // parenright.s1
    {5, 18, 0, -6, 5}, // parenright.s2
    {5, 21, 0, -7, 5}, // parenright.s3
    {5, 24, 0, -9, 5}, // parenright.s4
    {5, 27, 0, -10, 6}, // parenright.s5
    {6, 30, 0, -12, 6}, // parenright.s6
    {6, 32, 0, -13, 6}, // parenright.s7
    {6, 35, 0, -14, 7}, // parenright.s8
    {6, 38, 0, -16, 7}, // parenright.s9
    {6, 41, 0, -17, 7}, // parenright.s10
    {7, 44, 0, -19, 7}, // parenright.s11
    {7, 47, 0, -20, 8}, // parenright.s12
    {6, 16, 0, 0, 6}, // uni239E
    {3, 16, 3, -1, 6}, // uni239F
    {6, 16, 0, 0, 6}, // uni23A0
};
inline constexpr StixParenInk kStixParens8[] = {
    {3, 9, 0, -2, 3}, // parenleft
    {3, 10, 0, -3, 3}, // parenleft.s1
    {3, 12, 0, -4, 3}, // parenleft.s2
    {3, 14, 0, -5, 3}, // parenleft.s3
    {4, 16, 0, -6, 4}, // parenleft.s4
    {4, 18, 0, -7, 4}, // parenleft.s5
    {4, 20, 0, -8, 4}, // parenleft.s6
    {5, 22, 0, -9, 4}, // parenleft.s7
    {5, 24, 0, -10, 4}, // parenleft.s8
    {5, 26, 0, -11, 5}, // parenleft.s9
    {5, 28, 0, -12, 5}, // parenleft.s10
    {5, 30, 0, -13, 5}, // parenleft.s11
    {5, 32, 0, -14, 5}, // parenleft.s12
    {4, 11, 0, 0, 4}, // uni239B
    {2, 11, 0, -1, 4}, // uni239C
    {4, 11, 0, 0, 4}, // uni239D
    {3, 9, 0, -2, 3}, // parenright
    {3, 10, 0, -3, 3}, // parenright.s1
    {3, 12, 0, -4, 3}, // parenright.s2
    {3, 14, 0, -5, 3}, // parenright.s3
    {3, 16, 0, -6, 4}, // parenright.s4
    {4, 18, 0, -7, 4}, // parenright.s5
    {4, 20, 0, -8, 4}, // parenright.s6
    {4, 22, 0, -9, 4}, // parenright.s7
    {4, 24, 0, -10, 4}, // parenright.s8
    {4, 26, 0, -11, 5}, // parenright.s9
    {4, 28, 0, -12, 5}, // parenright.s10
    {5, 30, 0, -13, 5}, // parenright.s11
    {5, 32, 0, -14, 5}, // parenright.s12
    {4, 11, 0, 0, 4}, // uni239E
    {2, 11, 2, -1, 4}, // uni239F
    {4, 11, 0, 0, 4}, // uni23A0
};
} // namespace vpam
