/*
 * NumOS — STIX Two Math Italics Correction Table
 * Auto-generated by scripts/extract_stix_math.py on 2026-06-04 22:34:02
 * Source font: C:\Users\Juan Ramón\Documents\Calculadora\assets\fonts\STIXTwoMath-Regular.ttf
 * Font UPM (unitsPerEm): 1000
 *
 * This file is part of NumOS.
 * Copyright (C) 2026 Juan Ramon
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * DO NOT EDIT MANUALLY — regenerated at build time.
 */

#pragma once

#include <cstdint>
#include <algorithm>

namespace vpam {

/// Single entry in the italic correction table.
/// Sorted by codepoint for binary search (std::lower_bound).
struct ItalicsCorrectionEntry {
    uint32_t codepoint;   ///< Unicode scalar value
    int16_t  correction;  ///< Italic correction in font design units (UPM=1000)
};

/// Total number of italic correction entries.
constexpr uint16_t kItalicsCorrectionCount = 413;

/// Sorted array of italic correction values keyed by Unicode codepoint.
/// Find corrections via std::lower_bound on the codepoint field.
constexpr ItalicsCorrectionEntry kItalicsCorrectionTable[] = {
    { 0x210B,   40 },  // U+210B
    { 0x210E,   10 },  // U+210E
    { 0x210F,   10 },  // U+210F
    { 0x2110,   55 },  // U+2110
    { 0x2112,   10 },  // U+2112
    { 0x2113,   25 },  // U+2113
    { 0x211B,   10 },  // U+211B
    { 0x212C,   20 },  // U+212C
    { 0x2130,   20 },  // U+2130
    { 0x2131,   60 },  // U+2131
    { 0x2133,   40 },  // U+2133
    { 0x2145,   25 },  // U+2145
    { 0x2146,   35 },  // U+2146
    { 0x2148,   35 },  // U+2148
    { 0x2149,   35 },  // U+2149
    { 0x222B,  230 },  // U+222B
    { 0x222C,  230 },  // U+222C
    { 0x222D,  230 },  // U+222D
    { 0x222E,  230 },  // U+222E
    { 0x222F,  230 },  // U+222F
    { 0x2230,  230 },  // U+2230
    { 0x2231,  230 },  // U+2231
    { 0x2232,  230 },  // U+2232
    { 0x2233,  230 },  // U+2233
    { 0x2A0C,  230 },  // U+2A0C
    { 0x2A0D,  230 },  // U+2A0D
    { 0x2A0E,  230 },  // U+2A0E
    { 0x2A0F,  230 },  // U+2A0F
    { 0x2A10,  230 },  // U+2A10
    { 0x2A11,  230 },  // U+2A11
    { 0x2A12,  230 },  // U+2A12
    { 0x2A13,  230 },  // U+2A13
    { 0x2A14,  230 },  // U+2A14
    { 0x2A15,  230 },  // U+2A15
    { 0x2A16,  230 },  // U+2A16
    { 0x2A17,  230 },  // U+2A17
    { 0x2A18,  230 },  // U+2A18
    { 0x2A19,  230 },  // U+2A19
    { 0x2A1A,  230 },  // U+2A1A
    { 0x2A1B,  230 },  // U+2A1B
    { 0x2A1C,  230 },  // U+2A1C
    { 0xE155,   20 },  // U+E155
    { 0xE156,   50 },  // U+E156
    { 0xE157,   80 },  // U+E157
    { 0xE158,   20 },  // U+E158
    { 0xE159,   20 },  // U+E159
    { 0xE15A,   30 },  // U+E15A
    { 0xE15B,   50 },  // U+E15B
    { 0xE15D,   20 },  // U+E15D
    { 0xE15E,   25 },  // U+E15E
    { 0xE15F,   15 },  // U+E15F
    { 0xE160,   90 },  // U+E160
    { 0xE161,   40 },  // U+E161
    { 0xE162,  100 },  // U+E162
    { 0xE163,   80 },  // U+E163
    { 0xE164,   70 },  // U+E164
    { 0xE165,  100 },  // U+E165
    { 0xE169,  120 },  // U+E169
    { 0xE16D,   35 },  // U+E16D
    { 0xE177,   45 },  // U+E177
    { 0xE178,   35 },  // U+E178
    { 0xE17A,   45 },  // U+E17A
    { 0xE1B4,   40 },  // U+E1B4
    { 0xE1B5,   20 },  // U+E1B5
    { 0xE1B6,   20 },  // U+E1B6
    { 0xE1B7,   40 },  // U+E1B7
    { 0xE1B8,   25 },  // U+E1B8
    { 0xE1B9,   25 },  // U+E1B9
    { 0xE1BA,   45 },  // U+E1BA
    { 0xE1BB,   85 },  // U+E1BB
    { 0xE1C0,   10 },  // U+E1C0
    { 0xE1C1,   70 },  // U+E1C1
    { 0xE1C3,   40 },  // U+E1C3
    { 0xE1C4,   35 },  // U+E1C4
    { 0xE1C5,   10 },  // U+E1C5
    { 0xE1C6,   15 },  // U+E1C6
    { 0xE1C7,   10 },  // U+E1C7
    { 0xE1C8,   50 },  // U+E1C8
    { 0xE1CA,   10 },  // U+E1CA
    { 0xE1CB,   10 },  // U+E1CB
    { 0xE1CC,   25 },  // U+E1CC
    { 0xE1CD,   15 },  // U+E1CD
    { 0xE1CE,   10 },  // U+E1CE
    { 0xE1CF,   30 },  // U+E1CF
    { 0xE1D0,   15 },  // U+E1D0
    { 0xE1D1,   20 },  // U+E1D1
    { 0xE1D2,   80 },  // U+E1D2
    { 0xE1D3,   90 },  // U+E1D3
    { 0xE1D4,   20 },  // U+E1D4
    { 0xE1D5,   60 },  // U+E1D5
    { 0xE1D6,   60 },  // U+E1D6
    { 0xE1D7,   15 },  // U+E1D7
    { 0xE1D9,   20 },  // U+E1D9
    { 0xE1DB,   30 },  // U+E1DB
    { 0xE1DD,   90 },  // U+E1DD
    { 0xE1DF,   25 },  // U+E1DF
    { 0xE1E5,   95 },  // U+E1E5
    { 0xE1F2,   25 },  // U+E1F2
    { 0x1D435,   30 },  // U+1D435
    { 0x1D436,   50 },  // U+1D436
    { 0x1D437,   20 },  // U+1D437
    { 0x1D438,   30 },  // U+1D438
    { 0x1D439,   65 },  // U+1D439
    { 0x1D43A,   25 },  // U+1D43A
    { 0x1D43B,   45 },  // U+1D43B
    { 0x1D43C,   45 },  // U+1D43C
    { 0x1D43D,   60 },  // U+1D43D
    { 0x1D43E,   65 },  // U+1D43E
    { 0x1D440,   45 },  // U+1D440
    { 0x1D441,   65 },  // U+1D441
    { 0x1D442,   20 },  // U+1D442
    { 0x1D443,   35 },  // U+1D443
    { 0x1D444,   20 },  // U+1D444
    { 0x1D445,   15 },  // U+1D445
    { 0x1D446,   30 },  // U+1D446
    { 0x1D447,   65 },  // U+1D447
    { 0x1D448,   75 },  // U+1D448
    { 0x1D449,  100 },  // U+1D449
    { 0x1D44A,  100 },  // U+1D44A
    { 0x1D44B,   80 },  // U+1D44B
    { 0x1D44C,  110 },  // U+1D44C
    { 0x1D44D,   35 },  // U+1D44D
    { 0x1D44F,    5 },  // U+1D44F
    { 0x1D451,   20 },  // U+1D451
    { 0x1D453,   20 },  // U+1D453
    { 0x1D456,   20 },  // U+1D456
    { 0x1D457,   20 },  // U+1D457
    { 0x1D458,    5 },  // U+1D458
    { 0x1D459,   20 },  // U+1D459
    { 0x1D461,   15 },  // U+1D461
    { 0x1D463,   15 },  // U+1D463
    { 0x1D464,   15 },  // U+1D464
    { 0x1D465,   10 },  // U+1D465
    { 0x1D466,   15 },  // U+1D466
    { 0x1D467,   10 },  // U+1D467
    { 0x1D469,   30 },  // U+1D469
    { 0x1D46A,   50 },  // U+1D46A
    { 0x1D46B,   20 },  // U+1D46B
    { 0x1D46C,   30 },  // U+1D46C
    { 0x1D46D,   65 },  // U+1D46D
    { 0x1D46E,   25 },  // U+1D46E
    { 0x1D46F,   45 },  // U+1D46F
    { 0x1D470,   45 },  // U+1D470
    { 0x1D471,   60 },  // U+1D471
    { 0x1D472,   65 },  // U+1D472
    { 0x1D474,   45 },  // U+1D474
    { 0x1D475,   65 },  // U+1D475
    { 0x1D476,   20 },  // U+1D476
    { 0x1D477,   35 },  // U+1D477
    { 0x1D478,   20 },  // U+1D478
    { 0x1D479,   15 },  // U+1D479
    { 0x1D47A,   30 },  // U+1D47A
    { 0x1D47B,   65 },  // U+1D47B
    { 0x1D47C,   75 },  // U+1D47C
    { 0x1D47D,  100 },  // U+1D47D
    { 0x1D47E,  100 },  // U+1D47E
    { 0x1D47F,   80 },  // U+1D47F
    { 0x1D480,  110 },  // U+1D480
    { 0x1D481,   35 },  // U+1D481
    { 0x1D483,    5 },  // U+1D483
    { 0x1D485,   20 },  // U+1D485
    { 0x1D487,   10 },  // U+1D487
    { 0x1D489,    5 },  // U+1D489
    { 0x1D48A,   20 },  // U+1D48A
    { 0x1D48B,   70 },  // U+1D48B
    { 0x1D48C,    5 },  // U+1D48C
    { 0x1D48D,   20 },  // U+1D48D
    { 0x1D495,    1 },  // U+1D495
    { 0x1D497,   15 },  // U+1D497
    { 0x1D498,   15 },  // U+1D498
    { 0x1D499,   10 },  // U+1D499
    { 0x1D49A,   15 },  // U+1D49A
    { 0x1D49B,   10 },  // U+1D49B
    { 0x1D49C,   20 },  // U+1D49C
    { 0x1D49E,   40 },  // U+1D49E
    { 0x1D49F,   30 },  // U+1D49F
    { 0x1D4A2,   40 },  // U+1D4A2
    { 0x1D4A5,   50 },  // U+1D4A5
    { 0x1D4A6,   40 },  // U+1D4A6
    { 0x1D4A9,   55 },  // U+1D4A9
    { 0x1D4AA,   30 },  // U+1D4AA
    { 0x1D4AB,   30 },  // U+1D4AB
    { 0x1D4AC,   30 },  // U+1D4AC
    { 0x1D4AE,   20 },  // U+1D4AE
    { 0x1D4AF,   65 },  // U+1D4AF
    { 0x1D4B0,   45 },  // U+1D4B0
    { 0x1D4B1,   70 },  // U+1D4B1
    { 0x1D4B2,   70 },  // U+1D4B2
    { 0x1D4B3,   40 },  // U+1D4B3
    { 0x1D4B4,   50 },  // U+1D4B4
    { 0x1D4B5,   10 },  // U+1D4B5
    { 0x1D4B7,   20 },  // U+1D4B7
    { 0x1D4B9,  110 },  // U+1D4B9
    { 0x1D4BB,  110 },  // U+1D4BB
    { 0x1D4BD,   20 },  // U+1D4BD
    { 0x1D4BE,   20 },  // U+1D4BE
    { 0x1D4BF,   20 },  // U+1D4BF
    { 0x1D4C0,   20 },  // U+1D4C0
    { 0x1D4C1,   80 },  // U+1D4C1
    { 0x1D4C7,   50 },  // U+1D4C7
    { 0x1D4C9,   15 },  // U+1D4C9
    { 0x1D4CB,   40 },  // U+1D4CB
    { 0x1D4CC,   40 },  // U+1D4CC
    { 0x1D4D0,   20 },  // U+1D4D0
    { 0x1D4D1,   20 },  // U+1D4D1
    { 0x1D4D2,   40 },  // U+1D4D2
    { 0x1D4D3,   30 },  // U+1D4D3
    { 0x1D4D4,   30 },  // U+1D4D4
    { 0x1D4D5,   70 },  // U+1D4D5
    { 0x1D4D6,   30 },  // U+1D4D6
    { 0x1D4D7,   50 },  // U+1D4D7
    { 0x1D4D8,   60 },  // U+1D4D8
    { 0x1D4D9,   50 },  // U+1D4D9
    { 0x1D4DA,   50 },  // U+1D4DA
    { 0x1D4DB,   10 },  // U+1D4DB
    { 0x1D4DC,   60 },  // U+1D4DC
    { 0x1D4DD,   65 },  // U+1D4DD
    { 0x1D4DE,   30 },  // U+1D4DE
    { 0x1D4DF,   30 },  // U+1D4DF
    { 0x1D4E0,   30 },  // U+1D4E0
    { 0x1D4E1,   20 },  // U+1D4E1
    { 0x1D4E2,   10 },  // U+1D4E2
    { 0x1D4E3,   65 },  // U+1D4E3
    { 0x1D4E4,   54 },  // U+1D4E4
    { 0x1D4E5,   75 },  // U+1D4E5
    { 0x1D4E6,   75 },  // U+1D4E6
    { 0x1D4E7,   40 },  // U+1D4E7
    { 0x1D4E8,   50 },  // U+1D4E8
    { 0x1D4E9,   10 },  // U+1D4E9
    { 0x1D4EB,   20 },  // U+1D4EB
    { 0x1D4ED,  110 },  // U+1D4ED
    { 0x1D4EF,  110 },  // U+1D4EF
    { 0x1D4F1,   20 },  // U+1D4F1
    { 0x1D4F2,   20 },  // U+1D4F2
    { 0x1D4F3,   20 },  // U+1D4F3
    { 0x1D4F4,   20 },  // U+1D4F4
    { 0x1D4F5,   80 },  // U+1D4F5
    { 0x1D4FB,   50 },  // U+1D4FB
    { 0x1D4FD,   15 },  // U+1D4FD
    { 0x1D4FF,   40 },  // U+1D4FF
    { 0x1D500,   40 },  // U+1D500
    { 0x1D609,   10 },  // U+1D609
    { 0x1D60A,   30 },  // U+1D60A
    { 0x1D60B,   15 },  // U+1D60B
    { 0x1D60C,   40 },  // U+1D60C
    { 0x1D60D,   70 },  // U+1D60D
    { 0x1D60E,   10 },  // U+1D60E
    { 0x1D60F,   10 },  // U+1D60F
    { 0x1D610,   10 },  // U+1D610
    { 0x1D611,   20 },  // U+1D611
    { 0x1D612,   50 },  // U+1D612
    { 0x1D613,    5 },  // U+1D613
    { 0x1D614,   10 },  // U+1D614
    { 0x1D615,   10 },  // U+1D615
    { 0x1D616,   15 },  // U+1D616
    { 0x1D617,   30 },  // U+1D617
    { 0x1D618,   15 },  // U+1D618
    { 0x1D619,   25 },  // U+1D619
    { 0x1D61A,   15 },  // U+1D61A
    { 0x1D61B,   80 },  // U+1D61B
    { 0x1D61C,   20 },  // U+1D61C
    { 0x1D61D,   90 },  // U+1D61D
    { 0x1D61E,   70 },  // U+1D61E
    { 0x1D61F,   60 },  // U+1D61F
    { 0x1D620,   90 },  // U+1D620
    { 0x1D621,   35 },  // U+1D621
    { 0x1D623,    5 },  // U+1D623
    { 0x1D625,   25 },  // U+1D625
    { 0x1D627,  110 },  // U+1D627
    { 0x1D62A,   25 },  // U+1D62A
    { 0x1D62B,   25 },  // U+1D62B
    { 0x1D62C,    5 },  // U+1D62C
    { 0x1D62D,   25 },  // U+1D62D
    { 0x1D633,   30 },  // U+1D633
    { 0x1D635,   20 },  // U+1D635
    { 0x1D637,   35 },  // U+1D637
    { 0x1D638,   15 },  // U+1D638
    { 0x1D639,   35 },  // U+1D639
    { 0x1D63A,   40 },  // U+1D63A
    { 0x1D63B,   10 },  // U+1D63B
    { 0x1D63D,   10 },  // U+1D63D
    { 0x1D63E,   30 },  // U+1D63E
    { 0x1D63F,   15 },  // U+1D63F
    { 0x1D640,   40 },  // U+1D640
    { 0x1D641,   60 },  // U+1D641
    { 0x1D642,   10 },  // U+1D642
    { 0x1D643,   10 },  // U+1D643
    { 0x1D644,   10 },  // U+1D644
    { 0x1D645,   20 },  // U+1D645
    { 0x1D646,   40 },  // U+1D646
    { 0x1D647,    5 },  // U+1D647
    { 0x1D648,   10 },  // U+1D648
    { 0x1D649,   10 },  // U+1D649
    { 0x1D64A,   15 },  // U+1D64A
    { 0x1D64B,   30 },  // U+1D64B
    { 0x1D64C,   15 },  // U+1D64C
    { 0x1D64D,   25 },  // U+1D64D
    { 0x1D64E,   15 },  // U+1D64E
    { 0x1D64F,   80 },  // U+1D64F
    { 0x1D650,   20 },  // U+1D650
    { 0x1D651,   90 },  // U+1D651
    { 0x1D652,   70 },  // U+1D652
    { 0x1D653,   60 },  // U+1D653
    { 0x1D654,   90 },  // U+1D654
    { 0x1D655,   35 },  // U+1D655
    { 0x1D657,    5 },  // U+1D657
    { 0x1D659,   45 },  // U+1D659
    { 0x1D65B,  120 },  // U+1D65B
    { 0x1D65D,    5 },  // U+1D65D
    { 0x1D65E,   45 },  // U+1D65E
    { 0x1D65F,   45 },  // U+1D65F
    { 0x1D660,    5 },  // U+1D660
    { 0x1D661,   45 },  // U+1D661
    { 0x1D667,   40 },  // U+1D667
    { 0x1D669,   30 },  // U+1D669
    { 0x1D66B,   35 },  // U+1D66B
    { 0x1D66C,   15 },  // U+1D66C
    { 0x1D66D,   35 },  // U+1D66D
    { 0x1D66E,   40 },  // U+1D66E
    { 0x1D66F,   10 },  // U+1D66F
    { 0x1D6A4,    5 },  // U+1D6A4
    { 0x1D6A5,    5 },  // U+1D6A5
    { 0x1D6E3,   30 },  // U+1D6E3
    { 0x1D6E4,   80 },  // U+1D6E4
    { 0x1D6E6,   35 },  // U+1D6E6
    { 0x1D6E7,   35 },  // U+1D6E7
    { 0x1D6E8,   45 },  // U+1D6E8
    { 0x1D6E9,   20 },  // U+1D6E9
    { 0x1D6EA,   45 },  // U+1D6EA
    { 0x1D6EB,   65 },  // U+1D6EB
    { 0x1D6ED,   45 },  // U+1D6ED
    { 0x1D6EE,   65 },  // U+1D6EE
    { 0x1D6EF,   35 },  // U+1D6EF
    { 0x1D6F1,   55 },  // U+1D6F1
    { 0x1D6F2,   35 },  // U+1D6F2
    { 0x1D6F4,   30 },  // U+1D6F4
    { 0x1D6F5,   65 },  // U+1D6F5
    { 0x1D6F6,   80 },  // U+1D6F6
    { 0x1D6F7,   20 },  // U+1D6F7
    { 0x1D6F8,   80 },  // U+1D6F8
    { 0x1D6F9,   80 },  // U+1D6F9
    { 0x1D6FA,   20 },  // U+1D6FA
    { 0x1D6FB,   80 },  // U+1D6FB
    { 0x1D6FD,   30 },  // U+1D6FD
    { 0x1D6FF,   20 },  // U+1D6FF
    { 0x1D701,   20 },  // U+1D701
    { 0x1D703,   25 },  // U+1D703
    { 0x1D705,   10 },  // U+1D705
    { 0x1D709,   25 },  // U+1D709
    { 0x1D715,   15 },  // U+1D715
    { 0x1D717,   25 },  // U+1D717
    { 0x1D71D,   30 },  // U+1D71D
    { 0x1D71E,   80 },  // U+1D71E
    { 0x1D720,   30 },  // U+1D720
    { 0x1D721,   35 },  // U+1D721
    { 0x1D722,   45 },  // U+1D722
    { 0x1D723,   20 },  // U+1D723
    { 0x1D724,   45 },  // U+1D724
    { 0x1D725,   65 },  // U+1D725
    { 0x1D727,   45 },  // U+1D727
    { 0x1D728,   65 },  // U+1D728
    { 0x1D729,   35 },  // U+1D729
    { 0x1D72A,   20 },  // U+1D72A
    { 0x1D72B,   55 },  // U+1D72B
    { 0x1D72C,   35 },  // U+1D72C
    { 0x1D72D,   20 },  // U+1D72D
    { 0x1D72E,   30 },  // U+1D72E
    { 0x1D72F,   65 },  // U+1D72F
    { 0x1D730,   90 },  // U+1D730
    { 0x1D731,   20 },  // U+1D731
    { 0x1D732,   80 },  // U+1D732
    { 0x1D733,   80 },  // U+1D733
    { 0x1D734,   20 },  // U+1D734
    { 0x1D735,   80 },  // U+1D735
    { 0x1D737,   30 },  // U+1D737
    { 0x1D739,   40 },  // U+1D739
    { 0x1D73B,   70 },  // U+1D73B
    { 0x1D73D,   35 },  // U+1D73D
    { 0x1D73F,   20 },  // U+1D73F
    { 0x1D743,   50 },  // U+1D743
    { 0x1D74C,   15 },  // U+1D74C
    { 0x1D74F,   20 },  // U+1D74F
    { 0x1D751,   30 },  // U+1D751
    { 0x1D791,   10 },  // U+1D791
    { 0x1D792,   70 },  // U+1D792
    { 0x1D794,   40 },  // U+1D794
    { 0x1D795,   35 },  // U+1D795
    { 0x1D796,   10 },  // U+1D796
    { 0x1D797,   15 },  // U+1D797
    { 0x1D798,   10 },  // U+1D798
    { 0x1D799,   50 },  // U+1D799
    { 0x1D79B,   10 },  // U+1D79B
    { 0x1D79C,   10 },  // U+1D79C
    { 0x1D79D,   25 },  // U+1D79D
    { 0x1D79E,   15 },  // U+1D79E
    { 0x1D79F,   10 },  // U+1D79F
    { 0x1D7A0,   30 },  // U+1D7A0
    { 0x1D7A1,   15 },  // U+1D7A1
    { 0x1D7A2,   20 },  // U+1D7A2
    { 0x1D7A3,   80 },  // U+1D7A3
    { 0x1D7A4,   90 },  // U+1D7A4
    { 0x1D7A5,   20 },  // U+1D7A5
    { 0x1D7A6,   60 },  // U+1D7A6
    { 0x1D7A7,   60 },  // U+1D7A7
    { 0x1D7A8,   15 },  // U+1D7A8
    { 0x1D7A9,   85 },  // U+1D7A9
    { 0x1D7AB,   20 },  // U+1D7AB
    { 0x1D7AD,   30 },  // U+1D7AD
    { 0x1D7AF,   90 },  // U+1D7AF
    { 0x1D7B1,   25 },  // U+1D7B1
    { 0x1D7B7,   95 },  // U+1D7B7
    { 0x1D7C3,   20 },  // U+1D7C3
    { 0x1D7C5,   25 },  // U+1D7C5
};

/// Look up the italic correction for a given Unicode codepoint.
/// Returns the correction in design units, or 0 if not found.
/// O(log N) via binary search.
inline int16_t lookupItalicsCorrection(uint32_t codepoint) {
    const auto* end = kItalicsCorrectionTable + kItalicsCorrectionCount;
    const auto* it = std::lower_bound(
        kItalicsCorrectionTable, end, codepoint,
        [](const ItalicsCorrectionEntry& e, uint32_t cp) {
            return e.codepoint < cp;
        });
    if (it != end && it->codepoint == codepoint)
        return it->correction;
    return 0;
}

}  // namespace vpam
