#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Build only U+0394 from the renamed Latin Modern Math subset; lv_font_conv 1.5.3.

Optional --upstream creates the renamed subset from pinned Latin Modern Math.
Ordinary regeneration is offline, from the checked-in single-glyph subset.
"""
import argparse, hashlib, re, subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
UPSTREAM_SHA = '6075562b771f8b82f0c179e363389684f2dd09de30038269e2628e504bd7be0f'

def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--converter', default='lv_font_conv')
    p.add_argument('--upstream', type=Path)
    a = p.parse_args()
    subset = ROOT / 'assets/fonts/NumOSDiscriminant.otf'
    if a.upstream:
        from fontTools import subset as ft
        from fontTools.ttLib import TTFont
        assert hashlib.sha256(a.upstream.read_bytes()).hexdigest() == UPSTREAM_SHA
        font = TTFont(a.upstream, recalcTimestamp=False)
        options = ft.Options()
        options.layout_features = []
        sub = ft.Subsetter(options=options)
        sub.populate(unicodes=[0x0394])
        sub.subset(font)
        for rec in font['name'].names:
            if rec.nameID in (1, 3, 4, 6, 16):
                rec.string = 'NumOSDiscriminant'.encode(rec.getEncoding())
        if 'CFF ' in font:
            cff = font['CFF '].cff
            cff.fontNames = ['NumOSDiscriminant']
            cff.topDictIndex[0].FamilyName = 'NumOSDiscriminant'
            cff.topDictIndex[0].FullName = 'NumOSDiscriminant'
        font.save(subset)
    for size in (18, 12, 8):
        dest = ROOT / f'src/fonts/tex_delta_{size}.c'
        subprocess.run([a.converter, '--font', str(subset), '--size', str(size),
                        '--bpp', '4', '--format', 'lvgl', '--range', '0x0394',
                        '--no-compress', '--no-kerning', '-o', str(dest)], check=True)
        text = dest.read_text().replace('#include "lvgl/lvgl.h"', '#include "lvgl.h"')
        text = re.sub(r' \* Opts:.*\n', ' * Generated by scripts/generate-discriminant-font.py\n', text)
        text = ('/* Single U+0394 glyph derived from Latin Modern Math.\n'
                ' * Copyright 2012-2014 B. Jackowski, P. Strzelczyk and P. Pianowski.\n'
                ' * GUST Font License; see assets/fonts/LICENSES/GUST-FONT-LICENSE.txt\n'
                ' * Renamed subset: NumOSDiscriminant. DO NOT EDIT MANUALLY.\n */\n' + text)
        dest.write_text(text, encoding='utf-8')

if __name__ == '__main__':
    main()
