"""PlatformIO target for a standard, production-only merged factory image.

The target composes artifacts generated by the pinned Arduino/PlatformIO build.
It does not probe hardware, erase flash, alter image headers, or reuse the CAM
provisioning contract.
"""

from pathlib import Path
import subprocess
import sys

Import("env")  # noqa: F821 - supplied by PlatformIO/SCons


FLASH_BYTES = 16 * 1024 * 1024


def merge_factory_image(source, target, env):
    build_dir = Path(env.subst("$BUILD_DIR"))
    framework_dir = Path(
        env.PioPlatform().get_package_dir("framework-arduinoespressif32")
    )
    esptool_dir = Path(env.PioPlatform().get_package_dir("tool-esptoolpy"))

    bootloader = build_dir / "bootloader.bin"
    partitions = build_dir / "partitions.bin"
    application = build_dir / f"{env.subst('$PROGNAME')}.bin"
    boot_app0 = framework_dir / "tools" / "partitions" / "boot_app0.bin"
    output = build_dir / "numos-production-pcba-factory.bin"

    components = (
        (0x000000, bootloader, 0x008000),
        (0x008000, partitions, 0x001000),
        (0x00E000, boot_app0, 0x002000),
        (0x010000, application, 0x640000),
    )
    for offset, path, bound in components:
        if not path.is_file():
            raise RuntimeError(f"missing factory-image component: {path}")
        if path.stat().st_size > bound:
            raise RuntimeError(
                f"{path.name} size {path.stat().st_size} exceeds "
                f"0x{bound:x} bound at 0x{offset:x}"
            )

    command = [
        sys.executable,
        str(esptool_dir / "esptool.py"),
        "--chip",
        "esp32s3",
        "merge_bin",
        "--output",
        str(output),
        "--flash_mode",
        "keep",
        "--flash_freq",
        "keep",
        "--flash_size",
        "keep",
        "--fill-flash-size",
        "16MB",
    ]
    for offset, path, _ in components:
        command.extend((hex(offset), str(path)))

    subprocess.run(command, check=True)
    if output.stat().st_size != FLASH_BYTES:
        raise RuntimeError(
            f"factory image is {output.stat().st_size} bytes, expected "
            f"{FLASH_BYTES}"
        )
    print(f"Production factory image: {output} ({FLASH_BYTES} bytes)")


env.AddCustomTarget(
    name="factory_image",
    dependencies="$BUILD_DIR/${PROGNAME}.bin",
    actions=merge_factory_image,
    title="Production factory image",
    description="Merge standard ESP32-S3 artifacts into a padded 16 MB image",
)
